apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.fullnameOverride }}-pvc
    {{- if .Values.namespace }}
    namespace: {{ .Values.namespace.value }}
    {{- end }}
    labels:
        app: {{ .Values.fullnameOverride }}
spec:
    resources:
        requests:
            storage: 2Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: {{ .Values.fullnameOverride }}-fast-sc