apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-svc
  {{- if .Values.namespace.enabled }}
  namepsace: {{ .Values.namespace.value }}
  {{- end }}
  labels:
    app: {{ .Values.namespace.value }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.http.portProtocol }}
      name: {{ .Values.service.http.portName }}
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
  selector:
    app: {{ .Values.fullnameOverride }}