apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.fullnameOverride }}-fast-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
parameters:
  type: pd-ssd
