apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.value }}
  {{- end }}
  labels:
    app: {{ .Values.fullnameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride }}
  template:
    metadata:
      {{- if .Values.namespace.value }}
      namespace: {{ .Values.namespace.value }}
      {{- end }}
      labels:
        app: {{ .Values.fullnameOverride }}
    spec:
      containers:
        - name: {{ .Values.fullnameOverride }}
          {{- if eq .Values.image.tag "" }}
          image: "{{ .Values.image.repository }}:latest"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
  revisionHistoryLimit: {{ .Values.replicaset.revisionHistoryLimit }}