apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.value }}
  {{- end }}
  labels:
    app: {{ .Values.fullnameOverride }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.fullnameOverride }}
  type: LoadBalancer