apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer