apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
  selector:
    app: {{ .Values.fullnameOverride }}
  type: LoadBalancer